### PR TITLE
Issue 13 Resolved - Please Review for Merge

### PR DESCRIPTION
**Pull request by jy8474np**
Removed "DONE" from line 27 of ui.py

### CODE REVIEW

**Review by alicia-mctc — APPROVED** [review]
It looks good.

**Comment by jy8474np** [comment]
Great- Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by alicia-mctc — APPROVED** [review]
It looks good.

**Comment by jy8474np** [comment]
Thank you.

**Pull request merged**
